services:
  bff:
    image: aoirint/aoirint_mcping_bff:0.3.0
    restart: always
    environment:
      - MCPING_BFF_CORS_ALLOW_ORIGINS=${MCPING_BFF_CORS_ALLOW_ORIGINS:?}
      - MCPING_WEB_API_URL=${MCPING_WEB_API_URL:?}
      - MCPING_WEB_API_READ_API_KEY=${MCPING_WEB_API_READ_API_KEY:?}

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - bff
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN:?}
